import {NavigationProp} from '@react-navigation/native';

export type AppStackParamList = {
  Home: undefined;
  Login: undefined;
  Verification: undefined;
  VerificationStatus: undefined;
  CustomDateRange: undefined;
  Tabs: undefined;
  Report: undefined;
  ReportDetails: undefined;
  Trash: undefined;
  TrashDetails: undefined;
  Floor: undefined;
  FloorDetails: undefined;
  Restroom: undefined;
  RestroomDetails: undefined;
  User: undefined;
  UserDetails: undefined;
  Schedule: undefined;
  ScheduleDetails: undefined;
  Leave: undefined;
  LeaveDetails: undefined;
  WorkerReport: undefined;
  WorkerReportDetails: undefined;
  CreateWorkerReport: undefined;
  ChangePassword: undefined;
  EditProfile: undefined;
  LeaveRequest: undefined;
  LeaveRequestDetails: undefined;
  Calendar: undefined;
  CalendarSupervisor: undefined;
  CreateLeaveRequest: undefined;
  Employees: undefined;
  Sensor: undefined;
  SensorDetails: undefined;
  Area: undefined;
  AreaDetails: undefined;
  NotificationDetails: undefined;
  Notification: undefined;
  CreateReport: undefined;
  Request: undefined;
  RequestDetails: undefined;
  CreateRequest: undefined;
  CheckInOut: undefined;
  CheckInOutDetails: undefined;
  WorkerDashboard: undefined;
  ForgotPassword: undefined;
  SupervisorReport: undefined;
  CreateSupervisorReport: undefined;
  SupervisorReportDetails: {reportId: string};
};
export type StackNavigation = NavigationProp<AppStackParamList>;
